dataset:
  name: cifar10
  args:
    batch_size: 64
    image_size: 64

model:
  name: Diffusers
  vae: BaseVAE
  encoder: DiffusersEncoder
  decoder: DiffusersDecoder
  distribution: DiagonalGaussianDistribution
  args:
    in_channels: 3
    latent_channels: 4
    out_channels: 3

trainer:
  name: vae_trainer
  args:
    epochs: 200
    lr: 0.001
    pretrained_path: ./results/Diffusers/img_size_64/checkpoints/model_epoch_200.pt
    
