dataset:
  name: cifar10
  args:
    batch_size: 64
    image_size: 32

model:
  vae: BaseVAE
  encoder: SmallEncoder
  decoder: SmallDecoder
  distribution: DiagonalGaussianDistribution
  args:
    latent_dim: 64

trainer:
  name: vae_trainer
  args:
    epochs: 200
    lr: 0.001
    save_dir: './results/img_size_32'
    
