dataset:
  name: cifar10
  args:
    batch_size: 64
    image_size: 64

model:
  vae: BaseVAE
  encoder: SmallEncoder
  decoder: SmallDecoder
  distribution: DiagonalGaussianDistribution
  args:
    latent_dim: 64

trainer:
  name: vae_trainer
  args:
    epochs: 50

training:
  lr: 0.001